### PR TITLE
added demo for different ways of layering textures

### PR DESCRIPTION
**Pull request by QbieShay**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.
    - [x] You updated the docs or changelog.

**What kind of change does this PR introduce?**
This PR adds a new demo for mixing textures. No other files were changed or modified. The assets weight 2.8 MB in total (meshes + textures)

https://user-images.githubusercontent.com/7917475/112764226-da812680-9007-11eb-96fb-c6df848a4e68.mp4

### CODE REVIEW

**Comment by NathanLovato** [comment]
I'm getting errors here, both in Godot 3.2.3 and 3.3 RC7. The textures won't display in the editor and in-game.

Screenshot from 2021-03-31 08-50-10

Here are the errors

<details> 
  <summary>Error log </summary>
WARNING: instance: Parent path './MixVertexColor/RootNode (gltf orientation matrix)/RootNode (model correction matrix)/f842613eb44046c1bd1d95da846e9f2efbx/RootNode/rockFInal_LOD0' for node 'rockFInal_LOD0_lambert2_0' has vanished when instancing: 'res://Demos/TextureMixDemo.tscn'.
   At: scene/resources/packed_scene.cpp:100.
WARNING: instance: Parent path './MixAmbientOcclusion/RootNode (gltf orientation matrix)/RootNode (model correction matrix)/f842613eb44046c1bd1d95da846e9f2efbx/RootNode/rockFInal_LOD0' for node 'rockFInal_LOD0_lambert2_0' has vanished when instancing: 'res://Demos/TextureMixDemo.tscn'.
   At: scene/resources/packed_scene.cpp:100.
WARNING: instance: Parent path './MixWorldNormal/RootNode (gltf orientation matrix)/RootNode (model correction matrix)/f842613eb44046c1bd1d95da846e9f2efbx/RootNode/rockFInal_LOD0' for node 'rockFInal_LOD0_lambert2_0' has vanished when instancing: 'res://Demos/TextureMixDemo.tscn'.
   At: scene/resources/packed_scene.cpp:100.
WARNING: instance: Node 'Demo/RootNode (gltf orientation matrix)' was modified from inside an instance, but it has vanished.
   At: scene/resources/packed_scene.cpp:151.
WARNING: instance: Parent path './Demo/RootNode (gltf orientation matrix)/RootNode (model correction matrix)' for node 'f842613eb44046c1bd1d95da846e9f2efbx' has vanished when instancing: 'res://Demos/TextureMixDemo.tscn'.
   At: scene/resources/packed_scene.cpp:100.
WARNING: instance: Parent path './Demo/RootNode (gltf orientation matrix)/RootNode (model correction matrix)/f842613eb44046c1bd1d95da846e9f2efbx/RootNode/rockFInal_LOD0' for node 'rockFInal_LOD0_lambert2_0' has vanished when instancing: 'res://Demos/TextureMixDemo.tscn'.
   At: scene/resources/packed_scene.cpp:100.
</details>

I haven't further experimented with it because of other work right now, but any idea what could cause that?

**Comment by QbieShay** [comment]
I will take a look. It might be that something was lost in the final compression of assets, and it still worked on my machine because I had everything imported. I will check.

**Comment by QbieShay** [comment]
By deleting the import folder I had the same issue that you show. I will fix it  before next Monday. It is a bit more complex because the animation player can't find the tracks anymore, so I have renamed the nodes in the gltf files to makes them easier to parse, and I'll have to do some manual editing of the tscn, and reconfigure the materials.

**Comment by NathanLovato** [comment]
Seems to be working well now, thanks!

**Pull request merged**
